### ISSUE TITLE
Introduce list (table) view in addition to tile view

### ISSUE THREAD

**Issue by romeokienzler** [machine-learning-exchange/mlx#160]
**Is your feature request related to a problem? Please describe.**
Tile view not suitable for larger number of managed assets

**Describe the solution you'd like**
Either drop the tile view or add a toggle switch to activate a list / table view with capabilities of:
- sorting
- filtering
- adding/removing properties (columns)
-

**Describe alternatives you've considered**
there are no alternatives

**Comment by ckadner** [comment]
We have a list view for admins which allows setting assets to be `published` and `featured`. This view should be enhanced to add `delete` and maybe other admin type functions. The list view here is mostly to enable bulk-updates.

For non-admin users a list view does not currently exist. We did not need one yet since we only have a small set of curated assets.

**Comment by ckadner** [comment]
Adding a `wontfix` label for now to indicate a lower priority. We can tackle this on at a later date.

**Comment by romeokienzler** [comment]
thanks @ckadner and @drewbutlerbb4 will close for now and update/reopen once needed
