### ISSUE TITLE
Add search functionality to UI

### ISSUE THREAD

**Issue by romeokienzler** [machine-learning-exchange/mlx#166]
**Is your feature request related to a problem? Please describe.**
When the number of assets grows, it will be hard to find relevant assets

**Describe the solution you'd like**
A wild card search should go over all assets and search through all meta data fields. The search term can be specified using an input field

**Describe alternatives you've considered**
Using the browser's built-in search function

![image](https://user-images.githubusercontent.com/5694071/127304400-c48b71b0-b206-4c8d-aa4b-abe0e7a72500.png)

**Comment by ckadner** [comment]
The API does support `list_{asset-type}` calls (i.e. `GET` `/models`) with a `filter` and `sort_by` attribute (i.e. `name`, `description`, `created_at`, ...). This also works globally for the entire catalog (`GET` `/catalog`).

The `filter` attribute of the `list_...` call can be used for any sub-string of any of the assets attributes (i.e. `name`, `description`, `created_at`, ...) in a key-value stringified JSON dict: for example: `filter='{"name": "MAX %"}'` to get all models with a name starting with "MAX ". Notice the `%` instead of `*` as a catch-all placeholder.

FYI @drewbutlerbb4

**Comment by ckadner** [comment]
@romeokienzler 

> A wild card search should go over all assets and search through all meta data fields. The search term can be specified using an input field

This would be a little tedious to implement with MySQL only storing a select subset of the metadata uploaded in the original YAML, and Minio not supporting indexed searches on the contents of the files stored in it.

The most feasible implementation would be to search by field, i.e. `name=MAX% created_at>2020` (similar to Github search terms like `is:issue is:open author:romeokienzler author:ckadner`), or, internally search `name`, `description`, `metadata`, ... etc fields that **_are_** stored in MySQL

**Comment by ckadner** [comment]
@drewbutlerbb4 has created PR #169 that does a search/filtering of featured assets of one asset type. That search is not using the API as described above. Instead it filters down from the full list of assets retrieved from the API.

**Comment by romeokienzler** [comment]
thanks @drewbutlerbb4 and @ckadner will close for now
