### ISSUE TITLE
Quickstart not working with docker-compose running on a remote machine

### ISSUE THREAD

**Issue by romeokienzler** [machine-learning-exchange/mlx#26]
**Describe the bug**

Error when starting quickstart on docker compose

**To Reproduce**

https://github.com/ckadner/mlx.git
cd mlx
git checkout docker-compose
docker-compose up
ERROR: Service 'dashboard' depends on service 'mlx-init' which is undefined.

**Expected behavior**
quickstart starts

**Screenshots**

**Environment**

 - OS: Ubuntu 18.04.5 LTS
 - Browser -
 - MLX Version see above
 - Docker version 20.10.2, build 20.10.2-0ubuntu1~18.04.2
- docker-compose version 1.29.2, build 5becea4c

**Additional context**

**Comment by ckadner** [comment]
I had renamed the `mlx-init` service to `catalog` without updating the service name under the `dashboard` service. Apparently my Docker compose client still found the service under the old name, so I did not notice this inconsistency.

Should be fixed with [this commit](https://github.com/machine-learning-exchange/mlx/pull/25/commits/5e49fa1ec62a78abc40b52f3d7d05e5a6d9b42d6#diff-77e6cdd74f79d90bd9c86abe7a52f87af02950209523017bcf4cff8c94badf23R91)

**Comment by ckadner** [comment]
Huh, interesting, I did not mean to close this issue. Seems like merely linking this issue to the PR closed this issue.

**Comment by ckadner** [comment]
@romeokienzler
