### ISSUE TITLE
Quickstart UI missing upload functionality

### ISSUE THREAD

**Issue by romeokienzler** [machine-learning-exchange/mlx#97]
**Describe the bug**
The Quickstart UI is missing any upload functionality

**To Reproduce**
Deploy quickstart on docker-compose and start the UI - you won't see any upload buttons

**Expected behavior**

Upload buttons/functionality available as in kubernetes version

**Environment**

 - OS: RHEL 8.x
 - Browser FF
 - MLX Version 29c79a1463c7c0ebd55d6a34760e607ab669d7e5

**Additional context**

Quickstart is supposed to give users a full experience on how to manage assets. adding, updating and deleting is important in the UI as well

**Comment by ckadner** [comment]
Thanks @romeokienzler 

@drewbutlerbb4 @yhwang -- while with Docker Compose, we don't have KFP, we can't launch pipelines, we should however be able to upload, delete assets.

Can we bring up the UI in admin mode by default in Docker Compose using env variables or the settings file, without requiring a login by the user, since the user running Docker Compose is the "admin" in this local context.
